import type { Config } from "tailwindcss";
import animate from "tailwindcss-animate";

const config: Config = {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: { "2xl": "1400px" },
    },
    extend: {
      colors: {
        // ── Shadcn semantic tokens ───────────────────────────────────────────
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // ── SAKSHI brand palette ─────────────────────────────────────────────
        navy: {
          50:  "#eef2f9",
          100: "#d5dff0",
          200: "#aabfe1",
          300: "#7a99ce",
          400: "#4d73b8",
          500: "#2952a3",
          600: "#1e3f87",
          700: "#162f6b",
          800: "#0f2050",
          900: "#091435",
          950: "#050c21",
        },
        royal: {
          50:  "#eff6ff",
          100: "#dbeafe",
          200: "#bfdbfe",
          300: "#93c5fd",
          400: "#60a5fa",
          500: "#3b82f6",
          600: "#2563eb",
          700: "#1d4ed8",
          800: "#1e40af",
          900: "#1e3a8a",
          950: "#172554",
        },
        emerald: {
          50:  "#ecfdf5",
          100: "#d1fae5",
          200: "#a7f3d0",
          300: "#6ee7b7",
          400: "#34d399",
          500: "#10b981",
          600: "#059669",
          700: "#047857",
          800: "#065f46",
          900: "#064e3b",
          950: "#022c22",
        },
        amber: {
          50:  "#fffbeb",
          100: "#fef3c7",
          200: "#fde68a",
          300: "#fcd34d",
          400: "#fbbf24",
          500: "#f59e0b",
          600: "#d97706",
          700: "#b45309",
          800: "#92400e",
          900: "#78350f",
          950: "#451a03",
        },
        danger: {
          50:  "#fff1f2",
          100: "#ffe4e6",
          200: "#fecdd3",
          300: "#fda4af",
          400: "#fb7185",
          500: "#f43f5e",
          600: "#e11d48",
          700: "#be123c",
          800: "#9f1239",
          900: "#881337",
          950: "#4c0519",
        },
        success: {
          50:  "#f0fdf4",
          100: "#dcfce7",
          500: "#22c55e",
          600: "#16a34a",
          700: "#15803d",
        },
        slate: {
          50:  "#f8fafc",
          100: "#f1f5f9",
          200: "#e2e8f0",
          300: "#cbd5e1",
          400: "#94a3b8",
          500: "#64748b",
          600: "#475569",
          700: "#334155",
          800: "#1e293b",
          900: "#0f172a",
          950: "#020617",
        },
        // ── Sidebar tokens ───────────────────────────────────────────────────
        sidebar: {
          DEFAULT:           "hsl(var(--sidebar-bg))",
          foreground:        "hsl(var(--sidebar-fg))",
          border:            "hsl(var(--sidebar-border))",
          accent:            "hsl(var(--sidebar-accent))",
          "accent-foreground":"hsl(var(--sidebar-accent-fg))",
          ring:              "hsl(var(--sidebar-ring))",
        },
      },
      // ── Typography ─────────────────────────────────────────────────────────
      fontFamily: {
        sans: ["Inter", "system-ui", "-apple-system", "sans-serif"],
        mono: ["JetBrains Mono", "Fira Code", "Consolas", "monospace"],
        display: ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "2xs": ["0.625rem", { lineHeight: "0.875rem" }],
        xs:   ["0.75rem",  { lineHeight: "1rem" }],
        sm:   ["0.875rem", { lineHeight: "1.25rem" }],
        base: ["1rem",     { lineHeight: "1.5rem" }],
        lg:   ["1.125rem", { lineHeight: "1.75rem" }],
        xl:   ["1.25rem",  { lineHeight: "1.75rem" }],
        "2xl":["1.5rem",   { lineHeight: "2rem" }],
        "3xl":["1.875rem", { lineHeight: "2.25rem" }],
        "4xl":["2.25rem",  { lineHeight: "2.5rem" }],
        "5xl":["3rem",     { lineHeight: "1" }],
      },
      fontWeight: {
        thin:       "100",
        extralight: "200",
        light:      "300",
        normal:     "400",
        medium:     "500",
        semibold:   "600",
        bold:       "700",
        extrabold:  "800",
        black:      "900",
      },
      // ── Spacing ────────────────────────────────────────────────────────────
      spacing: {
        "4.5": "1.125rem",
        "5.5": "1.375rem",
        "13":  "3.25rem",
        "15":  "3.75rem",
        "18":  "4.5rem",
        "22":  "5.5rem",
        "30":  "7.5rem",
        "68":  "17rem",
        "72":  "18rem",
        "80":  "20rem",
        "88":  "22rem",
        "96":  "24rem",
      },
      // ── Border radius ──────────────────────────────────────────────────────
      borderRadius: {
        none: "0",
        sm:   "calc(var(--radius) - 4px)",
        DEFAULT:"var(--radius)",
        md:   "calc(var(--radius) - 2px)",
        lg:   "var(--radius)",
        xl:   "calc(var(--radius) + 4px)",
        "2xl":"calc(var(--radius) + 8px)",
        "3xl":"1.5rem",
        full: "9999px",
      },
      // ── Shadows ────────────────────────────────────────────────────────────
      boxShadow: {
        "xs":    "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        "sm":    "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
        DEFAULT: "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
        "md":    "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
        "lg":    "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
        "xl":    "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)",
        "2xl":   "0 25px 50px -12px rgb(0 0 0 / 0.25)",
        "card":  "0 0 0 1px hsl(var(--border)), 0 2px 4px -1px rgb(0 0 0 / 0.06)",
        "card-hover":"0 0 0 1px hsl(var(--border)), 0 8px 20px -4px rgb(0 0 0 / 0.12)",
        "focus": "0 0 0 3px hsl(var(--ring) / 0.35)",
      },
      // ── Keyframes & animations ─────────────────────────────────────────────
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to:   { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to:   { height: "0" },
        },
        "fade-in":       { from: { opacity: "0" }, to: { opacity: "1" } },
        "fade-out":      { from: { opacity: "1" }, to: { opacity: "0" } },
        "slide-in-up":   { from: { transform: "translateY(8px)",  opacity: "0" }, to: { transform: "translateY(0)",  opacity: "1" } },
        "slide-in-down": { from: { transform: "translateY(-8px)", opacity: "0" }, to: { transform: "translateY(0)",  opacity: "1" } },
        "slide-in-left": { from: { transform: "translateX(-8px)", opacity: "0" }, to: { transform: "translateX(0)", opacity: "1" } },
        "slide-in-right":{ from: { transform: "translateX(8px)",  opacity: "0" }, to: { transform: "translateX(0)", opacity: "1" } },
        "scale-in":      { from: { transform: "scale(0.95)", opacity: "0" }, to: { transform: "scale(1)", opacity: "1" } },
        "spin-slow":     { from: { transform: "rotate(0deg)" }, to: { transform: "rotate(360deg)" } },
        "pulse-soft":    { "0%,100%": { opacity: "1" }, "50%": { opacity: "0.6" } },
        "shimmer": {
          "0%":   { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition:  "200% 0" },
        },
        "progress": {
          from: { width: "0%" },
          to:   { width: "var(--progress-width)" },
        },
      },
      animation: {
        "accordion-down":  "accordion-down 0.2s ease-out",
        "accordion-up":    "accordion-up 0.2s ease-out",
        "fade-in":         "fade-in 0.2s ease-out",
        "fade-out":        "fade-out 0.2s ease-out",
        "slide-in-up":     "slide-in-up 0.25s ease-out",
        "slide-in-down":   "slide-in-down 0.25s ease-out",
        "slide-in-left":   "slide-in-left 0.25s ease-out",
        "slide-in-right":  "slide-in-right 0.25s ease-out",
        "scale-in":        "scale-in 0.2s ease-out",
        "spin-slow":       "spin-slow 2s linear infinite",
        "pulse-soft":      "pulse-soft 2s ease-in-out infinite",
        "shimmer":         "shimmer 1.8s infinite linear",
        "progress":        "progress 0.6s ease-out forwards",
      },
      // ── Transition ─────────────────────────────────────────────────────────
      transitionDuration: {
        "75":  "75ms",
        "100": "100ms",
        "150": "150ms",
        "200": "200ms",
        "300": "300ms",
        "500": "500ms",
        "700": "700ms",
      },
      // ── Z-index ────────────────────────────────────────────────────────────
      zIndex: {
        "0":    "0",
        "10":   "10",
        "20":   "20",
        "30":   "30",
        "40":   "40",
        "50":   "50",
        "sidebar":  "40",
        "topbar":   "50",
        "modal":    "100",
        "toast":    "200",
        "tooltip":  "300",
      },
    },
  },
  plugins: [animate],
};

export default config;
