import {
  LayoutDashboard,
  FolderOpen,
  GitBranch,
  Network,
  BrainCircuit,
  BarChart3,
  Bell,
  Building2,
  Shield,
  FlaskConical,
  Users,
  UserCog,
  Settings,
  LogOut,
  FileText,
  ClipboardList,
  AlertTriangle,
  CheckCircle2,
  XCircle,
  Info,
  Search,
  Plus,
  Edit,
  Trash2,
  Download,
  Upload,
  RefreshCw,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  Menu,
  X,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  Calendar,
  Clock,
  Filter,
  SortAsc,
  SortDesc,
  Home,
  Globe,
  Phone,
  Mail,
  MapPin,
  Printer,
  Share2,
  Link,
  ExternalLink,
  Copy,
  Save,
  SendHorizontal,
  Loader2,
  type LucideIcon,
} from "lucide-react";

// ─── Domain icon map ──────────────────────────────────────────────────────────
export const ICON_MAP: Record<string, LucideIcon> = {
  // Navigation
  dashboard:     LayoutDashboard,
  cases:         FolderOpen,
  timeline:      GitBranch,
  graph:         Network,
  ai:            BrainCircuit,
  analytics:     BarChart3,
  notifications: Bell,
  documents:     FileText,
  audit:         ClipboardList,
  settings:      Settings,
  logout:        LogOut,
  home:          Home,

  // Stakeholder portals
  hospital:      Building2,
  police:        Shield,
  fsl:           FlaskConical,
  cwc:           Users,
  supervisor:    UserCog,
  citizen:       Globe,

  // Actions
  search:        Search,
  add:           Plus,
  edit:          Edit,
  delete:        Trash2,
  download:      Download,
  upload:        Upload,
  refresh:       RefreshCw,
  save:          Save,
  send:          SendHorizontal,
  copy:          Copy,
  share:         Share2,
  print:         Printer,
  link:          Link,
  externalLink:  ExternalLink,

  // Status
  success:       CheckCircle2,
  error:         XCircle,
  warning:       AlertTriangle,
  info:          Info,
  loading:       Loader2,

  // UI
  close:         X,
  menu:          Menu,
  eye:           Eye,
  eyeOff:        EyeOff,
  lock:          Lock,
  unlock:        Unlock,
  chevronLeft:   ChevronLeft,
  chevronRight:  ChevronRight,
  chevronDown:   ChevronDown,
  chevronUp:     ChevronUp,
  filter:        Filter,
  sortAsc:       SortAsc,
  sortDesc:      SortDesc,
  calendar:      Calendar,
  clock:         Clock,

  // Contact
  phone:         Phone,
  mail:          Mail,
  mapPin:        MapPin,
} as const;

export type IconKey = keyof typeof ICON_MAP;
