"""initial schema

Revision ID: 9511e8f8df9f
Revises: 
Create Date: 2026-09-13 16:19:11.214312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9511e8f8df9f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('module', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('user', sa.String(length=140), nullable=False),
    sa.Column('user_role', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=120), nullable=True),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_entity_id', 'audit_logs', ['entity_id'], unique=False)
    op.create_index('ix_audit_logs_module', 'audit_logs', ['module'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_number', sa.String(length=120), nullable=False),
    sa.Column('fir_number', sa.String(length=120), nullable=False),
    sa.Column('crime_type', sa.String(length=80), nullable=False),
    sa.Column('victim_code', sa.String(length=80), nullable=False),
    sa.Column('victim_age', sa.Integer(), nullable=False),
    sa.Column('victim_gender', sa.String(length=10), nullable=False),
    sa.Column('incident_date', sa.String(length=80), nullable=False),
    sa.Column('incident_location', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=60), nullable=False),
    sa.Column('priority', sa.String(length=60), nullable=False),
    sa.Column('current_stage', sa.String(length=140), nullable=False),
    sa.Column('current_stage_order', sa.Integer(), nullable=False),
    sa.Column('total_stages', sa.Integer(), nullable=False),
    sa.Column('assigned_officer_id', sa.UUID(), nullable=True),
    sa.Column('assigned_officer', sa.String(length=140), nullable=True),
    sa.Column('assigned_station', sa.String(length=140), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('workflow', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('documents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number')
    )
    op.create_index('ix_cases_case_number', 'cases', ['case_number'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_roles_name', 'roles', ['name'], unique=True)
    op.create_table('court_readiness',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('readiness_percent', sa.Integer(), nullable=False),
    sa.Column('missing_items', sa.JSON(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_court_readiness_case_id', 'court_readiness', ['case_id'], unique=False)
    op.create_index('ix_court_readiness_status', 'court_readiness', ['status'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('uploaded_by', sa.String(length=140), nullable=False),
    sa.Column('uploaded_at', sa.String(length=80), nullable=False),
    sa.Column('size', sa.String(length=40), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_case_id', 'documents', ['case_id'], unique=False)
    op.create_index('ix_documents_uploaded_at', 'documents', ['uploaded_at'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.String(length=80), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('case_number', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('collected_by', sa.String(length=140), nullable=False),
    sa.Column('collected_by_role', sa.String(length=120), nullable=False),
    sa.Column('agency', sa.String(length=80), nullable=False),
    sa.Column('collection_date', sa.String(length=80), nullable=False),
    sa.Column('collection_time', sa.String(length=80), nullable=False),
    sa.Column('gps_location', sa.String(length=255), nullable=False),
    sa.Column('gps_coords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('current_custody', sa.String(length=80), nullable=False),
    sa.Column('current_officer', sa.String(length=140), nullable=False),
    sa.Column('initial_hash', sa.String(length=255), nullable=False),
    sa.Column('current_hash', sa.String(length=255), nullable=False),
    sa.Column('verification_status', sa.String(length=80), nullable=False),
    sa.Column('last_verified', sa.String(length=80), nullable=True),
    sa.Column('evidence_token', sa.String(length=140), nullable=False),
    sa.Column('seal_number', sa.String(length=120), nullable=False),
    sa.Column('weight', sa.String(length=80), nullable=True),
    sa.Column('dimensions', sa.String(length=80), nullable=True),
    sa.Column('photographs', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('chain', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('shares', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('audit_logs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidence_id')
    )
    op.create_index('ix_evidence_case_id', 'evidence', ['case_id'], unique=False)
    op.create_index('ix_evidence_evidence_id', 'evidence', ['evidence_id'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=80), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('case_number', sa.String(length=120), nullable=True),
    sa.Column('action_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_case_id', 'notifications', ['case_id'], unique=False)
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('contents', sa.JSON(), nullable=False),
    sa.Column('issued_by', sa.String(length=140), nullable=False),
    sa.Column('issued_at', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reports_case_id', 'reports', ['case_id'], unique=False)
    op.create_index('ix_reports_type', 'reports', ['report_type'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('risk_level', sa.String(length=80), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_factors', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_assessments_case_id', 'risk_assessments', ['case_id'], unique=False)
    op.create_index('ix_risk_assessments_risk_level', 'risk_assessments', ['risk_level'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('avatarUrl', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('stage_id', sa.String(length=120), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('completed_date', sa.String(length=80), nullable=True),
    sa.Column('officer', sa.String(length=140), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('deadline', sa.String(length=80), nullable=True),
    sa.Column('department', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workflows_case_id', 'workflows', ['case_id'], unique=False)
    op.create_index('ix_workflows_stage_id', 'workflows', ['stage_id'], unique=False)
    op.create_table('evidence_integrity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('hash_match', sa.Boolean(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.String(length=80), nullable=False),
    sa.Column('verified_by', sa.String(length=140), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_integrity_evidence_id', 'evidence_integrity', ['evidence_id'], unique=False)
    op.create_table('evidence_transfers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('from_agency', sa.String(length=80), nullable=False),
    sa.Column('to_agency', sa.String(length=80), nullable=False),
    sa.Column('officer', sa.String(length=140), nullable=False),
    sa.Column('officer_role', sa.String(length=120), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('transfer_id', sa.String(length=120), nullable=False),
    sa.Column('hash_before', sa.String(length=255), nullable=True),
    sa.Column('hash_after', sa.String(length=255), nullable=True),
    sa.Column('digital_signature', sa.String(length=255), nullable=False),
    sa.Column('verification_status', sa.String(length=80), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transfer_id')
    )
    op.create_index('ix_evidence_transfers_case_id', 'evidence_transfers', ['case_id'], unique=False)
    op.create_index('ix_evidence_transfers_evidence_id', 'evidence_transfers', ['evidence_id'], unique=False)
    op.create_table('evidence_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('modified_by', sa.String(length=140), nullable=False),
    sa.Column('modified_at', sa.String(length=80), nullable=False),
    sa.Column('changes', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('snapshot', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_versions_evidence_id', 'evidence_versions', ['evidence_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('department', sa.String(length=80), nullable=True),
    sa.Column('agency', sa.String(length=80), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_profiles_user_id', 'user_profiles', ['user_id'], unique=True)
    op.create_table('workflow_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('previous_status', sa.String(length=80), nullable=False),
    sa.Column('new_status', sa.String(length=80), nullable=False),
    sa.Column('changed_by', sa.String(length=140), nullable=False),
    sa.Column('changed_at', sa.String(length=80), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workflow_history_case_id', 'workflow_history', ['case_id'], unique=False)
    op.create_index('ix_workflow_history_workflow_id', 'workflow_history', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workflow_history_workflow_id', table_name='workflow_history')
    op.drop_index('ix_workflow_history_case_id', table_name='workflow_history')
    op.drop_table('workflow_history')
    op.drop_index('ix_user_profiles_user_id', table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index('ix_evidence_versions_evidence_id', table_name='evidence_versions')
    op.drop_table('evidence_versions')
    op.drop_index('ix_evidence_transfers_evidence_id', table_name='evidence_transfers')
    op.drop_index('ix_evidence_transfers_case_id', table_name='evidence_transfers')
    op.drop_table('evidence_transfers')
    op.drop_index('ix_evidence_integrity_evidence_id', table_name='evidence_integrity')
    op.drop_table('evidence_integrity')
    op.drop_index('ix_workflows_stage_id', table_name='workflows')
    op.drop_index('ix_workflows_case_id', table_name='workflows')
    op.drop_table('workflows')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_risk_assessments_risk_level', table_name='risk_assessments')
    op.drop_index('ix_risk_assessments_case_id', table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index('ix_reports_type', table_name='reports')
    op.drop_index('ix_reports_case_id', table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_index('ix_notifications_case_id', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_evidence_evidence_id', table_name='evidence')
    op.drop_index('ix_evidence_case_id', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index('ix_documents_uploaded_at', table_name='documents')
    op.drop_index('ix_documents_case_id', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_court_readiness_status', table_name='court_readiness')
    op.drop_index('ix_court_readiness_case_id', table_name='court_readiness')
    op.drop_table('court_readiness')
    op.drop_index('ix_roles_name', table_name='roles')
    op.drop_table('roles')
    op.drop_index('ix_cases_case_number', table_name='cases')
    op.drop_table('cases')
    op.drop_index('ix_audit_logs_module', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
