"""create_accountability_passports

Revision ID: 7bd0bde65aad
Revises: a1b2c3d4e5f6
Create Date: 2026-09-13 21:21:38.849929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7bd0bde65aad'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accountability_passports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('passport_id', sa.String(length=120), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('case_reference', sa.String(length=120), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('generated_by', sa.String(length=140), nullable=False),
    sa.Column('generated_by_id', sa.UUID(), nullable=False),
    sa.Column('procedural_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('obligation_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('audit_verification', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('integrity_reference', sa.String(length=64), nullable=False),
    sa.Column('passport_hash', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('passport_id')
    )
    op.create_index('ix_accountability_passports_case_id', 'accountability_passports', ['case_id'], unique=False)
    op.create_index('ix_accountability_passports_passport_id', 'accountability_passports', ['passport_id'], unique=True)
    op.alter_column('audit_logs', 'previous_hash',
               existing_type=sa.VARCHAR(length=64),
               server_default=None,
               existing_comment="SHA-256 of the previous event in chain, 'GENESIS' for first, 'LEGACY' for pre-chain rows.",
               existing_nullable=False)
    op.alter_column('audit_logs', 'event_hash',
               existing_type=sa.VARCHAR(length=64),
               server_default=None,
               existing_comment="SHA-256(canonical_payload + '|' + previous_hash)",
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'event_hash',
               existing_type=sa.VARCHAR(length=64),
               server_default=sa.text("'LEGACY'::character varying"),
               existing_comment="SHA-256(canonical_payload + '|' + previous_hash)",
               existing_nullable=False)
    op.alter_column('audit_logs', 'previous_hash',
               existing_type=sa.VARCHAR(length=64),
               server_default=sa.text("'LEGACY'::character varying"),
               existing_comment="SHA-256 of the previous event in chain, 'GENESIS' for first, 'LEGACY' for pre-chain rows.",
               existing_nullable=False)
    op.drop_index('ix_accountability_passports_passport_id', table_name='accountability_passports')
    op.drop_index('ix_accountability_passports_case_id', table_name='accountability_passports')
    op.drop_table('accountability_passports')
    # ### end Alembic commands ###
